stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - black --check module_30_ci_linters/homework/hw1
    - isort --check-only module_30_ci_linters/homework/hw1
    - flake8 module_30_ci_linters/homework/hw1
    - mypy module_30_ci_linters/homework/hw1

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pytest -v