image: python:3.11

stages:
  - lint
  - test

before_script:
  - pip install -r requirements.txt

# Линтеры
mypy:
  stage: lint
  script:
    - mypy module_30_ci_linters

black:
  stage: lint
  script:
    - black --diff --check module_30_ci_linters

isort:
  stage: lint
  script:
    - isort --check-only module_30_ci_linters

flake8:
  stage: lint
  script:
    - flake8 module_30_ci_linters

# Тесты
pytest:
  stage: test
  script:
    - pytest module_30_ci_linters/tests -v
