workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.11

stages:
  - build
  - test

before_script:
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest module_29_testing/tests

mypy:
  stage: test
  script:
    - mypy module_29_testing

black:
  stage: test
  script:
    - black --diff --check module_29_testing

isort:
  stage: test
  script:
    - isort --check-only module_29_testing

flake8:
  stage: test
  script:
    - flake8 module_29_testing