events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Отдача статики
        location /static/ {
            root C:/Users/magzh/PyCharmMiscProject/python_advanced/module_23_cgi_server/homework/task2;
        }

        # Проксирование запросов к WSGI-приложению
        location / {
            proxy_pass http://127.0.0.1:8000;
        }
    }
}
