version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: magzhan
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: skillbox_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    command: >
      postgres -c log_destination=stderr
               -c logging_collector=on
               -c log_directory=/var/log/postgresql

volumes:
  pgdata:

networks:
  appnet:
